allowBuilds:
  '@parcel/watcher': true
<<<<<<< HEAD
  '@tailwindcss/oxide': true
  electron: true
  esbuild: true
  javascript-obfuscator: true
=======
>>>>>>> 457044c57ea6141e665c88603ea84d7542da64a4
  unrs-resolver: true
  vue-demi: true
