allowBuilds:
  '@parcel/watcher': true
<<<<<<< HEAD
  '@tailwindcss/oxide': true
  electron: true
  esbuild: true
  javascript-obfuscator: true
=======
>>>>>>> c27dc311feeca88f575184c70cd539091ffeaf47
  unrs-resolver: true
  vue-demi: true
